app/main.dev.ts

Disables opening internal links in new application windows, and instead simply routes them back into the main application window.
- Overridden `windowOpenHandler` on mainwindow.
Closes #10

override window open handler

---

scripts/notarize.js

When doing notarization on macOS on a computer with multiple available providers the build fails. This change ensures that it selects the correct input to use.
Setting the `ascProvider` and added logging when notarization starts.

Add ascProvider and logging to notarization

---

app/components/AccountCard/AccountCard.module.scss

Fix the account card info overlay not appearing in production build.
Change opacity to use decimals instead of percentages.

Fix AccountCard info overlay in production

---

app/utils/cborHelper.ts

closes #48.
Changed CBOR encoder to use internal method to check for integer string instead of Number constructor.

Fix whitespace only memo being encoded as 0.

---

app/pages/Accounts/TransactionListElement.tsx
app/utils/TransactionConverters.ts

Fix #47
When converting incoming memos, use `JSON.stringify` on objects instead of `.toString()`.
Use `<pre>` tag when displaying memo, so it doesn't ignore white space characters.

Improve cbor memo display

---

app/components/PickAccount.tsx
app/features/AccountSlice.ts
app/pages/Accounts/AccountPageHeader.tsx
app/pages/multisig/AccountTransactions/CreateTransferProposal/CreateTransferProposal.tsx

Don't show pending accounts in multisig flow.
Closes #50.
Added `confirmedAccountsSelector`, which only returns confirmed accounts.
Use this new selector in multisig flow, which will cause pending and rejected accounts to not be in the list of accounts to choose.

Hide pending accounts in multisig flow

---

app/constants/errorMessages.json
app/features/TransactionSlice.ts
app/pages/Accounts/AccountView.tsx

Fix #41 .
Reworked updateTransactions to return a promise, that gets resolved/rejected when the updating is done or fails.
AccountView now catches rejections from updateTransactions and displays an error to the user.

Fix fetching transactions from wallet proxy failing silently

---

app/components/ChoiceModal.tsx
app/pages/Recovery/PerformRecovery.tsx

Closes #52
disableClose on recovery warning modal.
Fix controller, in recovery, not stopping recovery when aborted.
Fix \<p\> descendant of \<p\> error in ChoiceModal.

Account recovery stuck in waiting

---

app/components/Transfers/EncryptedTransfer.tsx
app/components/Transfers/ExternalTransfer/ExternalTransfer.tsx
app/components/Transfers/FinalPage.tsx
app/components/Transfers/InternalTransfer.tsx
app/components/Transfers/SimpleTransfer.tsx
app/components/Transfers/UnshieldAmount.tsx
app/components/Transfers/ensureNoPendingShieldedBalance.tsx
app/constants/routes.json
app/constants/transferLocations.json
app/database/TransactionDao.ts
app/database/migrations/20210914132103_add_indices_on_transaction_table.ts
app/pages/Accounts/AccountView.tsx
app/pages/Accounts/BuildSchedule/BuildSchedule.tsx
app/pages/Accounts/SubmitTransfer/SubmitTransfer.tsx
app/preload/database/transactionsDao.ts
app/preload/preloadTypes.ts
app/utils/transactionTypes.ts

Fix #45.
When the user tries to create a `shielded transfer` or a `unshield`, they get an error, if they have a pending `shield`/`unshield`/`shielded transfer`.
Now updates ledger component message in `SubmitTransfer.`
Refactored `FinalPage` out of Internal/External Transfer components, to simplify. (and avoid unnecessary calls to node)

Fix: Encrypted transfer fail if another is pending

---

app/database/TransactionDao.ts
app/database/migrations/20210914132103_add_indices_on_transaction_table.ts
app/features/AccountSlice.ts
app/features/TransactionSlice.ts
app/pages/Accounts/AccountView.tsx
app/preload/database/transactionsDao.ts
app/preload/preloadTypes.ts

Fix #67.
Stop loading all transactions when inserting transactions.
Rework AccountView effects so fetching transactions is not interrupted by accountInfo update.

Improve transaction insert efficiency

---

app/database/migrations/20210914132103_add_indices_on_transaction_table.ts
app/preload/database/transactionsDao.ts

Improve the performance of the latest transactions view on accounts.
- Added multi column indices.
- Dropped indices that are now unused to improve space usage.
- Updated queries so that they will use the multi column indices.
Note: The changes were made to an existing migration file, so either downgrade and up again, or start with a new database.

Use multi column indices to improve performance

---

app/pages/multisig/ProposalView/ProposalView.tsx
app/pages/multisig/ProposalView/SignatureCheckboxes/SignatureCheckboxes.tsx

Allow update instruction proposals to add more than the required number of signatures. 
Fix #74.
No longer disable signature input, when required number of signatures have been reached. (on update instructions)
Changed text above signature checkboxes to say "X of Y _required_ signatures".

Allow more than required number of signatures on update instructions

---

app/preload/database/transactionsDao.ts
app/preload/preloadTypes.ts

Fix constraint violations, which are happening, when loading transactions (on finalizer accounts).
Reworked insertTransactions and upsertTransactionsAndUpdateMaxId:
- Check for transaction existence using transactionHash _and id_.
- Changed insertTransactions to update transactionally like upsertTransactionsAndUpdateMaxId.
- Refactored most of the behaviour into common delegate functions.

Fix constraint violations on insert

---

app/pages/Accounts/AccountBalanceView/AccountDefaultButton.tsx
app/pages/Accounts/TransactionList/InfiniteTransactionList.tsx
app/pages/Accounts/TransactionList/TransactionList.module.scss

Shows a modal first time a default account is set, describing the action at what it implies. Also fixes a small style bug on transaction list elements introduced in #60 
- Show prompt modal when setting default account first time
- Hide top border for first transaction list element in list group.
Closes #91

Set default account description modal + transaction list element border bug

---

app/utils/printUtility.tsx

Long memos didn't break words properly on print. This ensures that happens
- Added word break css to print memo display
Closes #95

ensure word break on memo in print

---

app/components/BakerPendingChange/BakerPendingChange.tsx
app/node/NodeApiTypes.ts
app/utils/dataHooks.ts

Fix #101
Calculate baker state cooldown using `currentEraGenesisTime` instead of `genesisTime`.
Added `currentEraGenesisTime` and `currentEraGenesisBlock` to `ConsensusStatus` type.

Fixed bug where baker cooldown end date was incorrect

---

app/main.ts
app/main/menu.ts
app/pages/multisig/AccountTransactions/CreateTransferProposal/PickMemo.tsx

Fix #104
Make memo text error-colored on error in multisig flow.
Add context menu that allows cut/copy/paste and spellchecking.

Fix minor layout inconsistencies

---

app/pages/Accounts/AccountListPage/AccountList.tsx
app/pages/Accounts/AccountListPage/AccountView.tsx

Functions supposed to be inaccessible for non-confirmed accounts were accessible on the account page. This makes them inaccessible.
Closes #100 
- Remove list view details for rejected and pending accounts.
- Made pending and rejected accounts not clickable in list view (except when rejected account is the initial account of an identity - we need this to display a specific error modal)

Disable account details for non-confirmed accounts

---

app/main/ipcHandlers.ts

Disable going back to a previous external flow, like another provider's, by pressing back.
Clear the BrowserView's history when entering the external issuance view.

Disable going back to previous external view

---

app/main.ts

Currently if the external issuance flow tries to open a new window, it opens a new browser window in the app.
Intercept this command and open the website in external browser instead.

Block browserView opening internal views

---

app/features/TransactionSlice.ts
app/pages/Accounts/TransactionsHeader/TransactionsHeader.tsx

Transaction sync state was reset when changing view on account page. This fixes that.
- Only latest rejected/fulfilled update action sets sync state.

Latest rejected/fulfilled update request sets sync state

---

package.json

An issue in electron-updater meant that even if verification of an automatic update failed, then the update was still 
applied on macOS systems. This has been fixed on the newer version of electron-updater.
- Bump electron-updater from 4.3.4 to 4.3.9.

Update electron-updater dependency

---

scripts/disclaimer.js

Improve generation of license notices for the desktop wallet.
- Trailing spaces are removed (as they resulted in linting errors when building the documentation)
- Code blocks are now 'console' code blocks to avoid warnings when building in the documentation repository.

Remove trailing spaces from disclaimer

---

app/shell/Status/NodeStatus.tsx

I noticed our console was spammed with `setNodeStatus` state updates even when the state was not changing. This makes it so that the state update is only dispatched if it has changed.
- Check if the status has changed before updating the status state.
- Start the controller, so that `abort()` actually aborts.

Stop updating node status state on no change

---

app/utils/rustInterface.ts
rust-src/aux_functions.rs

After use-node-sdk, creating any of the three types of shielded balance transfers,
did not work. This fixes that.

Fix shielded balance transfers

---

app/pages/Accounts/AccountDetailsPage/AccountReport/AccountReport.tsx

Fix #162.
The error was caused by the modal closing and triggering onFinish automatically.
During account report, don't close decrypt modal between accounts.
This prevents the auto rejection of accounts. 

Fix multi-account report skipping accounts

---

app/preload/accountReport.ts

Improve the performance of the account report (significantly).
- Avoid using `fromDate` and `toDate` in as many queries to the wallet proxy as possible. Instead, use `from` and paginate over that and do the filtering in-memory. The wallet proxy does not perform well if we use queries with the dates.
- Removed filtering based on `smallestBlockTime` as it resulted in skipping transactions that should not have been skipped.

Improve performance of account report

---

app/components/ExportBakerCredentials.tsx

Fix baker keys export not following the format that the node expects. 
Now manually puts bakerId into the JSON output, to make it a JSON number.

Fix baker keys export

---

CHANGELOG.md
app/components/FailedIdentityModal.tsx
app/components/IdentityCard/FailedIdentityDetails.tsx
app/pages/Identities/IdentityView.tsx
app/preload/database/identityDao.ts
app/preload/preloadTypes.ts
app/utils/IdentityStatusPoller.ts

Notabene now provides error message details in the `detail` field. This PR ensures that we save that information on rejected identities, and that we display the message to the user.
- `detail` is saved in the identity table if the identity creation fails.
- the `detail` field is displayed for failed identities.

Display identity creation error details

---

app/components/DisplayIdentityAttributes.tsx
app/components/IdentityCard/IdentityCard.tsx
app/pages/Accounts/AccountDetailsPage/CredentialInformation/CredentialInformation.tsx
app/utils/basicHelpers.ts
app/utils/identityHelpers.ts

Implement #160.
Move DisplayIdentityAttributes to components, and have IdentityCard use it.
Handle unknown attributes by displaying those keys raw.
When sorting, unknown attributes are sorted higher.

Support displaying unknown attributes

---

app/features/TransactionSlice.ts

The reducer functions used to find `minId` and `maxId` used string comparisons, which lead to bugs where the transaction loading would keep loading the same transactions, instead of getting new transactions. This PR fixes that by calculating the correct `minId` and `maxId`.
As the transaction list state is sorted descendingly on the `id` field, the following changes are made to fix the issue:
- `maxId` is be found as the first item in the transaction state with an `id`.
- `minId` is found as the last item in the transaction state with an `id`.

Fix issues with finding min and max id

---

app/features/TransactionSlice.ts
app/pages/Accounts/DecryptComponent.tsx
app/preload/accountReport.ts
app/utils/decryptHelpers.ts

Currently we will attempt to decrypt a shielded transfer that has failed. This throws an error because such a transaction does not have the `encrypted` field anymore.
- Filter on status on the transactions before assuming they are to be decrypted.

Stop attempting to decrypt failed encrypted transfers

---

app/features/TransactionSlice.ts
app/pages/Accounts/TransactionList/GtuDrop.tsx
app/pages/Accounts/TransactionList/InfiniteTransactionList.tsx
app/pages/Accounts/useAccountSync.ts
app/preload/http.ts
app/preload/preloadTypes.ts

In some cases not all transactions were successfully loaded from the wallet proxy. This change updates the loading of transactions from the wallet proxy, so that we keep paginating until a full page is loaded, or until all transactions are loaded. This should ensure that we will not have missing transactions.
- Use transaction filter when loading shielded transactions. This also means that the wallet proxy will not be queried for reward transactions when we load shielded transactions.
- Filter away incoming shielded transactions when showing normal balance.
- When loading transactions keep loading until a full page (after filtering) has been received.
- Only load new transactions (on balance change, encrypted balance change) if no `toDate` has been set.

Fix transaction loading

---

app/pages/Accounts/AccountBalanceView/AccountBalanceView.module.scss

Fix that in the account view, You could only click on the balance button's _balan_ part.
Gave the viewing shielded buttons a higher z-index.

Fix balance button hitbox

---

app/features/AccountSlice.ts
app/pages/Accounts/SubmitTransaction/SubmitTransaction.tsx
app/utils/TransactionStatusPoller.ts

Fix bug, which caused shielded balance to become locked after sending shielded transfer.
Saves decrypted amount on finalization.

Bugfix: Shielded balance becomes locked after making a shielded transfer

---

app/pages/Accounts/TransactionList/GtuDrop.tsx
app/preload/database/transactionsDao.ts

Show pending transactions sent to an account. This includes transactions sent from another account in the desktop wallet and CCD drops.
- Monitor the CCD drop transaction to ensure that it is cleaned up from the database when it is confirmed or rejected.
- When loading transactions for an account we now include any pending transactions _to_ that account.

Also load pending transactions to an account

---

app/features/TransactionSlice.ts

A pending transaction does not have an `id` as the `id` is given by the wallet proxy. The value is `null` and not `undefined` and therefore the logic for finding the maximum `id` in the current transaction state was erroneous. This resulted in the application fetching transactions without supplying the `from` input to the wallet proxy, which results in the wrong transactions being loaded. This change fixes that so that the correct `maxId` is found.
- Also filter out any transactions with `transaction.id === null`.

Fix issue with wrong new transactions being fetched

---

app/features/AccountSlice.ts
app/pages/Accounts/useAccountSync.ts

updateAccountInfo now only performs updates, if there has been a change in the accountInfo.
updateAccountInfo effect in useAccountSync now uses timeouts to re-run the effect, instead of an interval (So it has access to the newest accountInfo)

Only update accountInfoEntry on change

---

.github/workflows/build-lint-test.yml
CHANGELOG.md
app/database/migrations/20211214152503_set_new_default_node.ts
app/pages/Home/SetNodeConnection/SetNodeConnection.tsx

Use Virtual Hive's public node as the default node in the desktop wallet. This should ease the use of the desktop wallet for users who do not wish to run their own node.
- Migrated any default node settings from `127.0.0.1` to `concordiumwalletnode.com`. The idea is that users who have already changed their settings probably do not want it forcibly updated.

Update default node

---

configs/webpack.config.renderer.dev.js
configs/webpack.config.renderer.prod.js
package.json

Fixes memo serialize and deserialize after webpack 5 upgrade 
- add process polyfill

add process depencency, as webpack 5 doesn't polyfill.

---

CHANGELOG.md
app/utils/identityHelpers.ts

Fix #210 
If formatting date fails for an identity attribute, return "N/A" instead of throwing an error.

Fix crash caused by empty date in identity attributes

---

package.json
scripts/build.js

Allow signing desktop wallet during packaging on windows.
Package on windows now tries to sign using our EV certificate.
added script "package-win-no-sign" to skip signing.

Windows sign during build

---

app/pages/multisig/updates/common/MintRateInput/MintRateInput.tsx

In Time parameters (and mint distribution on P3), setting mint rate to 0 caused a 0 to be appended the formula.
Fix #253

Fix incorrect mint formula, when value is zero

---

app/pages/multisig/updates/common/MintRateInput/MintRateInput.tsx

Fix #252
Mint rate yearly rate now uses js Number, to avoid large displays.
(So it show e-notation and approximations for values larger than MAX_SAFE_INTEGER)

Fix mintRate overflowing out of the screen

---

app/components/Transfers/configureDelegation/DelegationAmountPage.tsx
app/components/Transfers/configureDelegation/DelegationTargetPage.tsx
app/node/nodeHelpers.ts
app/node/nodeRequests.ts
app/preload/grpc.ts
app/preload/preloadTypes.ts
app/utils/transactionHelpers.ts

Fix #267, #269.
- Check if target pool is open for delegation in `DelegationTargetPage`.
- Check that delegated amount is not 0 in `DelegationAmountPage`.
- Rename getPoolInfo to getPoolStatus to match Node-api and types.

Check delegation target is open for delegation

---

app/components/DisplayAsQR.tsx
app/pages/Accounts/Accounts.module.scss
app/pages/Accounts/ShowAccountAddress.tsx
app/pages/Accounts/ShowAccountAddressFull.tsx
package.json
yarn.lock

Scale the QR code in full view, so it can fit on smaller screens.
Fix #277 
- Make a component that wraps `qrcode.react`, and controls the size, allowing it to be scalable.
- Remove account information in header on the full show account address page. (I remember discussing this with @jens-concordium but I forgot about it/never made an issue :upside_down_face:)

Scale QR code 

---

app/components/ClosingBakerPoolNotification.tsx
app/components/Notification/Notification.module.scss
app/features/NotificationSlice.ts
app/pages/Accounts/AccountDetailsPage/StakingDetails/StakingDetails.tsx
app/pages/Home/SelectPassword/SelectPassword.tsx
app/pages/Home/Unlock/Unlock.tsx
app/shell/Notifications/Notifications.tsx
app/styles/elements/_typography.scss
app/utils/init/closingBakerPoolChecker.ts
app/utils/init/initialize.ts
app/utils/timeHelpers.ts

Notify users (at startup) if they are currently delegating to a baker pool that is shutting down.
- At startup the application checks whether any delegating account is delegating to a pool that is in the process of closing. A notification is created for each account where this is the case.
- The delegation view now shows if the target pool is shutting down and includes when it will happen.

285 notify user of closing baker pool

---

CHANGELOG.md
app/pages/Accounts/TransactionView/TransactionView.module.scss
app/pages/Accounts/TransactionView/TransactionView.tsx
app/utils/TransactionConverters.ts
app/utils/types.ts

Fix #248, both the new configure and reward transactions have information hidden in the events 
Display transaction events in transaction view.

Display transaction events in transaction view

---

app/components/PickBakerStakeAmount.tsx
app/components/Transfers/configureDelegation/DelegationAmountPage.tsx
app/components/Transfers/configureDelegation/DelegationTargetPage.tsx
app/node/nodeHelpers.ts
app/pages/Accounts/AccountDetailsPage/StakingDetails/StakingDetails.tsx
app/preload/grpc.ts
app/preload/preloadTypes.ts
app/utils/init/closingBakerPoolChecker.ts

Improve typing of `getPoolStatus` as we know it is a baker pool status when a baker id is provided.
- Updated types from the generic `PoolStatus` to `BakerPoolStatus` as we never use the passive delegation status.

Better types for getPoolStatus

---

app/pages/Accounts/AccountDetailsPage/Baking/AddBaker.tsx
app/pages/Accounts/AccountDetailsPage/Baking/UpdateBakerPool.tsx
app/pages/multisig/AccountTransactions/AddBaker.tsx
app/pages/multisig/AccountTransactions/UpdateBakerPool.tsx
app/pages/multisig/updates/CooldownParameters/CooldownParametersView.tsx
app/pages/multisig/updates/CooldownParameters/UpdateCooldownParameters.tsx
app/pages/multisig/updates/MintDistribution/MintDistributionView.tsx
app/pages/multisig/updates/MintDistribution/UpdateMintDistribution.tsx
app/pages/multisig/updates/PoolParameters/PoolParametersView.tsx
app/pages/multisig/updates/PoolParameters/UpdatePoolParameters.tsx
app/pages/multisig/updates/TimeParameters/TimeParametersView.tsx
app/pages/multisig/updates/TimeParameters/UpdateTimeParameters.tsx
app/utils/blockSummaryHelpers.ts
app/utils/dataHooks.ts
app/utils/timeHelpers.ts
app/utils/transactionHandlers/BakerStakeThresholdHandler.tsx
app/utils/transactionHandlers/CooldownParametersHandler.tsx
app/utils/transactionHandlers/PoolParametersHandlers.tsx
app/utils/transactionHandlers/TimeParameterHandler.tsx

Some places we used type guards that the version (of some object) was not 1, and assuming then it was 0. Here we now check that it is 0 directly instead. (where we could)

Use V0 guards where applicable

---

app/pages/multisig/menu/MultiSignatureCreateProposalList.tsx
app/utils/transactionFlows/addDelegation.ts

Add delegation/_Register as a delegator_ was still called _delegate to a pool_ in the multisig flow.
_Delegate to a pool_ -> _Register as a delegator_

Fix 'add delegation' multisig name

---

scripts/build.js

Fixes check that windows should build without signing.

Fix windows build without signing

---

app/pages/multisig/updates/PoolParameters/PoolParametersShow.tsx
app/pages/multisig/updates/PoolParameters/UpdatePoolParameters.tsx

Noticed that in the pool parameters, a header still said L pool commissions.

Rename L pool header to passive delegation in PoolParameters

---

CHANGELOG.md
app/main.ts
app/main/autoUpdate/index.ts
app/main/autoUpdate/init.ts
app/main/ipcHandlers.ts
app/package.json

Fix a macOS specific issue where closing the main window (pressing `x` in the upper-left corner) causes both an error popup when the window is recreated, and also prevents the user from creating an identity until the application is completely restarted.
Note: This will result in a macOS specific update for testnet and mainnet.
- Remove ipc handlers and auto update event listeners when all windows are closed on macOS. This is only relevant on macOS, as on Linux and Windows the entire application is destroyed when the last window is closed. This ensures that we stop trying to create duplicate handlers and also that we don't keep old handlers with references to destroyed objects.

Cleanup handlers and listeners on all windows closed

---

CHANGELOG.md
app/package.json
app/preload/ledger/ledgerObserverImpl.ts
app/yarn.lock

Add support for the Ledger Nano S Plus.
- Updated dependency used for communicating with Ledger devices (to a version that also supports the Plus).
- Disabled the auto disconnect feature that was added to the used dependency (this keeps behavior like we are used to).
Note that we have a `type` column in the `wallet` table that is hardcoded to `ledgernanos` which will be incorrect for Plus devices. The column should be dropped (as we don't need it), but this is difficult with the current dependencies we are using. An upgrade to `knex` might make it a lot easier, but upgrading `knex` could be a major thing as they are 2 majors ahead of us. So this will go into the tech debt pile (https://github.com/Concordium/concordium-desktop-wallet/issues/325) for now due to the time constraints of …

Support Ledger Nano S Plus

---

app/components/ManualUpdateNotification.tsx
app/components/Transfers/configureDelegation/DelegationTargetPage.tsx
app/constants/urls.json

When delegating to a baker we want to provide help so that the user can find a nice pool to join.
- Now links to ccdscan/staking where baker pools can be found.
- Fixed the download page link in manual update notifications (rpm / deb) to point to mainnet instead of testnet.

Delegation link

---

CHANGELOG.md
app/package.json
app/utils/transactionHelpers.ts
test/utils/transactionHelpers.test.ts

Allow changing restake when below threshold
- Don't fail baker check if below threshold and chosen amount is equal to stake.
- Made some tests.
- Bumped version.

Allow changing restake when below threshold

---

CHANGELOG.md
app/package.json
app/preload/ledger/ledgerObserverImpl.ts
app/yarn.lock
package.json
yarn.lock

Fix a Ledger connectivity issue experienced on Windows.
- Add a USB detach event listener where we check if the Ledger is actually still connected.

Fix windows ledger connection issue

---

.github/workflows/release.yaml

set +e to not fail completely when awscli gives return code 254
Add set +e to shell command.
_Remove if not applicable.
By submitting the contribution I accept the terms and conditions of the
Contributor License Agreement v1.0
- link: https://developers.concordium.com/CLAs/Contributor-License-Agreement-v1.0.pdf

Add set +e to not fail on error code 254 from awscli

---

.github/workflows/release.yaml

Fixed issues with LinuxDeploy
This PR removes the manual Linuxdeploy AppImage creation step from the release.yaml workflow.
The AppImage is already generated automatically during the build process.
By submitting the contribution I accept the terms and conditions of the
Contributor License Agreement v1.0
- link: https://developers.concordium.com/CLAs/Contributor-License-Agreement-v1.0.pdf

Remove LinuxDeploy AppImage step from GitHub Actions workflow

---

CHANGELOG.md
app/constants/routes.json
app/pages/multisig/MultiSignatureCreateProposal/MultiSignatureCreateProposal.tsx
app/pages/multisig/MultiSignaturePage/MultiSignaturePage.tsx
app/pages/multisig/menu/MultiSignatureCreateProposalList.tsx

This PR adds a separate menu for governance transactions in the multi-signature panel.
- Remove governance transactions from the `Make new proposal` menu in `Multi signature transactions`.
- Add separate menu `Make new governance proposal` menu for governance transactions in `Multi signature transactions`. The menu is only visible if `Foundation transactions` is enabled in the settings.

Add Separate Menu for Governance Transaction

---

CHANGELOG.md
README.md
app/pages/multisig/updates/UpdateGovernanceKeys/UpdateAuthorizationKeys.tsx
app/pages/multisig/updates/UpdateGovernanceKeys/util.ts
app/utils/UpdateSerialization.ts
app/utils/types.ts

Related to: https://github.com/Concordium/concordium-ledger-app/pull/116
- Fix display of `new size of level 2 key set` which now accounts for removed keys correctly
- Update the flow for signing authorizations updates with support for v2 authorizations

Support v2 authorizations (COR-1766)

---

.github/workflows/release.yaml
app/preload/ledger/ledgerObserverImpl.ts
package.json

Resolving setup issues on Ubuntu and fixing blank screen problems when connecting to a Ledger device with the Governance app opened
**Fix CRE-52: Resolve setup issue in Desktop Wallet v1.7.3 on Ubuntu**
- Added "executableArgs": ["--no-sandbox"] to improve compatibility with Ubuntu environments.
- Updated CI/build scripts to build and install OpenSSL 1.1.1w from source, and configured runtime/build paths for OpenSSL. This ensures the wallet works reliably on Ubuntu systems.
**Fix CRE-518: Application screen gets blank when we connect with Ledger**
- Introduced a mutex to ensure only one part of the app can access the Ledger device at a time, reducing crashes and connection conflicts.
- Increased device polling timeout from 2000ms to 5000ms for better stability.
- Enhanced error logging: …

Bugfix: Resolve blank application screen on Ledger connect (CRE-518) and setup issue on Ubuntu v1.7.3 (CRE-52)

---

CHANGELOG.md
app/package.json
app/preload/ledger/ledgerObserverImpl.ts

Fix applied where the desktop wallet losses connection after doing a single transaction
The transport is closed, and the client is set to undefined in closeTransport(). This can cause the client to become unavailable even if the device is still connected, leading to issues when we try to use the Ledger after a cleanup or disconnect event.

Fix: CRE-582 Desktop wallet losses connection after doing single transaction
