Concordium/concordium-desktop-wallet

.github/workflows/build-lint-test.yml
Setting up the initial pipeline that mimics what we had in Gitlab.
Added a GitHub workflow file that allows for building, linting and testing the code.
=> Create initial CI pipeline

app/ipc/http.ts, app/package.json
Fix issue where identities fail because the URL has a `?` at the end even when there were no search parameters.
Note these changes are just moved manually from the Gitlab repository.
Merging in the release branch to main.
Do not insert `?` if there are no search parameters.
=> Fix issue with extra ? at the end of get URLs

app/utils/transactionHandlers/SimpleTransferHandler.tsx
closes #51
Fixed the type in the simple transfer handler.
=> Fix send gtu multisig header

app/shell/Status/LedgerStatus.tsx
Fix #38.
Fix OutDated typo in ledger status.
=> fix OutDated typo

app/main/ipcHandlers.ts, app/pages/IdentityIssuance/ExternalIssuance/ExternalIssuance.tsx, app/preload/database/identityDao.ts, app/preload/preloadTypes.ts
Fix issue where the identity provider was called on an incorrect URL.
- Now stops the browser view from following the redirect to the URL that contains the identity location.
- Fixed https://github.com/Concordium/concordium-desktop-wallet/issues/55.
=> Identity provider redirect bug

app/pages/multisig/AccountTransactions/CreateTransferProposal/CreateTransferProposal.tsx
re-add the filter isMultisig filter in multisig transfer flow.
re-add the filter in `CreateTransferFlow`
=> Readded isMultiSig filter in multisig transfer flows

app/pages/Accounts/AccountDetailsPage/TransactionLogFilters/TransactionLogFilters.module.scss, app/pages/Accounts/AccountDetailsPage/TransactionLogFilters/TransactionLogFilters.tsx
Rename transactionLogFilter buttons apply->search, save->"save filters".
Changed button text and css to make text fit.
=> Rename buttons in transactionLogFilters

app/features/ledger/ErrorCodes.ts
Handle locked error codes.
Added the missing error code to the Ledger error code map.
=> Add locked error code to error code map

app/pages/Accounts/AccountDetailsPage/AccountDetailsPage.tsx, app/pages/Accounts/AccountListPage/AccountListPage.tsx, app/pages/Accounts/AccountListPage/AccountView.tsx, app/pages/Accounts/AccountPage.tsx, app/pages/Accounts/useAccountSync.ts, app/pages/Accounts/withAccountSync.tsx
Fix to issues on account page:
- Scroll position maintained when switching accounts in list view
- Transaction list emptied when viewing unconfirmed accounts
=> Account page fixes

app/main.ts, app/package.json
single instance lock made mac builds fail for test/stagenet. Removing temporarily from mac build until it works.
=> remove lock from mac build

app/components/AccountCard/AccountCard.tsx, app/pages/Accounts/AccountBalanceView/AccountBalanceView.tsx, app/pages/Accounts/AccountDetailsPage/BuildSchedule/BuildSchedule.tsx, app/pages/Accounts/AccountPageHeader.tsx, app/pages/multisig/AccountTransactions/CreateTransferProposal/CreateTransferProposal.tsx, app/utils/accountHelpers.ts, app/utils/transactionHelpers.ts
Fix #92.
Change the validation when setting staked to allow using locked amount.
Fix display of account amount when baker and has locked amounts.
=> Allow locked amount to be staked

app/components/FailedIdentityModal.tsx, app/pages/Accounts/FailedInitialAccount.tsx
Fix #102  
Added more info in failed identity/account dialogs
=> Add more info in dialogs when identity fails.

app/components/CopyButton/CopyButton.tsx, app/components/IdentityCard/FailedIdentityDetails.tsx, app/components/IdentityCard/IdentityCard.module.scss, app/preload/preload.ts, app/preload/preloadTypes.ts, app/styles/config/_colors.scss
Fix #109
Updated failed identity view and contact support flow.
=> Updated failed identity view and contact support flow

app/pages/Accounts/AccountReport/util.ts, app/pages/Recovery/PerformRecovery.tsx
Fix #117 
+ Sneakily capitalize an i in account recovery.
=> Fix error when making account report

app/components/Form/util/validation.ts, app/components/TransactionFilters.tsx
=> fix validation based on current date

app/pages/exportImport/Import.tsx, app/preload/crypto.ts, app/utils/importHelpers.ts
Fix #120. 
Changed import to allow decrypting mobile wallets backups.
Detect mobile wallets on import, and display specific error for that.
=> Improve error when importing mobile wallet export

package.json
Removing a dependency that is not used for production.
- Remove the dependency from package.json.
=> Remove unused production dependency

app/preload/accountReport.ts
Fix #161
`archiver` is only finalized if not aborted.
=> Fix Cancelling multi-account report blocking subsequent tries

app/features/AccountSlice.ts, app/node/nodeHelpers.ts, app/pages/Accounts/useAccountSync.ts
Fix #174 
Only update accountInfo if current account if confirmed. 
Added some comments.
=> Fix error popping up when selecting non confirmed account

app/pages/Accounts/AccountBalanceView/AccountBalanceView.tsx
Show the baker ID when an account is baking.
- `toString()` the bigint so that it shows up.
=> Show baker id for bakers

CHANGELOG.md
=> Fixed a typo in the changelog

app/components/ButtonNavLink/ButtonNavLink.tsx
Fix the react error that happens on startup.
=> Fix activeClassName react error

app/pages/multisig/AccountTransactions/UpdateAccountCredentials/CreateUpdate.tsx
Fix update-credentials signing page looking weird while fetching information from node.
Changed loading component for credential update signing page.
=> Bugfix: update-credentials signing page looks weird without node connection

app/constants/ipcCommands.json, app/main/ipcHandlers.ts, app/pages/IdentityIssuance/IdentityIssuancePage.tsx, app/pages/IdentityIssuance/NavigationBlock.tsx, app/preload/preload.ts, app/preload/preloadTypes.ts
Fix #201
Instead of using the Prompt component to prompt user, use electron's messageBox,
because the Prompt component blocks the renderer thread, which seems to cause the issue with the input fields.
=> Fix unresponsive input fields after identityIssuance is aborted.

app/preload/http.ts
Fix #226 
Catch the error coming from JSON.parse and throw a nicer one instead.
=> Handle parse errors, when parsing getTransactions from wallet-proxy

CHANGELOG.md, app/components/TransactionFilters.tsx, app/constants/transactionKindNames.json, app/features/TransactionSlice.ts, app/utils/transactionHelpers.ts, app/utils/types.ts
Adds support for new reward types coming with the delegation protocol version in transaction list and account report.
Closes #238 
- Add new reward type to transaction kinds
- Adapt transaction list to support new reward type
- Add filter for new reward type
=> Delegation protocol rewards in list/export

app/components/Form/DatePicker/DatePicker.tsx, app/pages/multisig/MultiSignatureCreateProposal/BuildProposal.tsx, app/pages/multisig/MultiSignatureCreateProposal/MultiSignatureCreateProposal.tsx
Fixes #251 
- Ensure onblur event is triggered for datepicker when changing value.
=> Transaction expiry time error

app/pages/Accounts/AccountDetailsPage/AccountCarousel/AccountCarousel.module.scss, app/pages/Accounts/AccountDetailsPage/AccountCarousel/AccountCarousel.tsx
=> fix account carousel for single account wallet

app/store/store.tsx
=> fix browser history for windows (perhaps 11 only)

app/components/Transfers/configureDelegation/DelegationAmountPage.tsx, app/pages/Accounts/AccountBalanceView/AccountBalanceView.tsx
Fixes #268 
- Change text on delegation amount view to take target into account
- Align delegation label on account balance with mobile wallet 
=> revise text for delegation views

app/components/Transfers/configureDelegation/DelegationTargetPage.tsx
=> Check if new delegation target's cap would be violated

app/components/Transfers/configureDelegation/DelegationAmountPage.tsx, app/components/Transfers/configureDelegation/DelegationTargetPage.tsx, app/constants/ledgerConstants.json, app/features/ledger/SignPoolParameters.ts, app/node/nodeHelpers.ts, app/node/nodeRequests.ts, app/pages/Accounts/AccountBalanceView/AccountBalanceView.tsx, app/pages/Accounts/AccountDetailsPage/MoreActions.tsx, app/pages/Accounts/AccountDetailsPage/StakingDetails/StakingDetails.tsx, app/pages/multisig/updates/PoolParameters/PoolParametersShow.tsx, app/pages/multisig/updates/PoolParameters/PoolParametersView.tsx, app/pages/multisig/updates/PoolParameters/UpdatePoolParameters.tsx, app/pages/multisig/updates/PoolParameters/util.ts, app/pages/multisig/updates/UpdateGovernanceKeys/util.ts, app/utils/UpdateSerialization.ts, app/utils/transactionFlows/configureDelegation.ts, app/utils/transactionHandlers/BakerStakeThresholdHandler.tsx, app/utils/transactionHandlers/PoolParametersHandlers.tsx, app/utils/types.ts, package.json, yarn.lock
Fix #275.
- Rename L-pool to passive delegation.
- Update some text / labels to make more sense
- Update node SDK version
- Update minimum ledger version.
=> Lpool renaming

app/components/PickBakerStakeAmount.tsx, app/utils/dataHooks.ts
Fix #283
Display a warning, and the estimated limit, when breaching the capitalBound.
Created a hook for getting capitalBound.
=> Show a warning when baker stake exceeds the capital bound

app/components/BakerTransactions/BakerStakeSettings.tsx, app/components/PickBakerStakeAmount.tsx, app/components/Transfers/configureDelegation/DelegationAmountPage.tsx, app/pages/Accounts/AccountDetailsPage/Baking/OldBakerFlows/AddBaker/AddBaker.tsx, app/pages/Accounts/AccountDetailsPage/Baking/OldBakerFlows/RemoveBaker.tsx, app/pages/Accounts/AccountDetailsPage/Baking/OldBakerFlows/UpdateBakerRestake.tsx, app/pages/Accounts/AccountDetailsPage/Baking/OldBakerFlows/UpdateBakerStake.tsx, app/utils/dataHooks.ts
Fix #278
- Show when stake increase will take effect.
- Fix text that mentions 2 epochs.
=> Fix stake increase message

app/components/Transfers/configureBaker/MetadataUrlPage.tsx, app/utils/basicHelpers.ts, app/utils/transactionHelpers.ts
Fix #299
- Check that URL is ASCII only.
- Fix ASCII check function being flipped.
=> Validate url is ascii + fix ascii check

app/constants/transactionKindNames.json
Align name of new reward with mobile wallet
=> Align new reward name with MW

app/utils/node/RejectReasonHelper.ts, package.json, yarn.lock
support new reject reasons.
(Depends on new version of node-sdk with updated reject reasons)
Use RejectReason tags from node-sdk.
Add text for new rejectreasons.
=> Add new reject reasons

app/package.json
=> Bump prelease version (1.4.0-beta.3)

app/package.json
Bump version to 1.4.0 so that we can build the release for testnet.
- Updated version in package.json.
=> Bump version to 1.4.0

app/pages/Accounts/AccountDetailsPage/StakingDetails/StakingDetails.tsx, app/utils/transactionFlows/configureBaker.ts
#311 
- [] (If necessary) I have updated the CHANGELOG.
=> Dont show commission rates when pool is closed

CHANGELOG.md, app/components/Transfers/configureDelegation/DelegationTargetPage.tsx, app/constants/urls.json
Add link to documentation when choosing delegation target.
=> Add link to documentation in delegationTargetPage

scripts/build.js
=> Fix build without SIGNING variable

resources/html/terms.html
Update terms and conditions to also mention Nano S Plus. Updated it to align with what we host on the developer webpage.
- Updated terms and conditions.
=> Updated terms and conditions with Nano S Plus

app/components/ledger/util.ts, app/constants/ledgerConstants.json, app/node/nodeRequests.ts
Make chain updates work.
Fix interaction with governance app + fix serialization of chain updates
=> Fix interaction with governance app + fix serialization of chain updates

CHANGELOG.md, app/features/ledger/ConcordiumLedgerClient.ts, app/features/ledger/ConcordiumLedgerClientMain.ts, app/pages/multisig/menu/MultiSignatureCreateProposalList.tsx, app/pages/multisig/updates/BlockEnergyLimit/BlockEnergyLimitView.tsx, app/pages/multisig/updates/BlockEnergyLimit/UpdateBlockEnergyLimit.tsx, app/preload/ledger/ledger.ts, app/preload/preloadLedgerTypes.ts, app/utils/UpdateSerialization.ts, app/utils/blockSummaryHelpers.ts, app/utils/protocolVersion.ts, app/utils/transactionHandlers/BlockEnergyLimitHandler.tsx, app/utils/transactionHandlers/HandlerFinder.ts, app/utils/types.ts, app/utils/withUpdateQueue.tsx
Support the new BlockEnergyLimit Update.
- Added the flow for the update.
- Added a check for consensus update protocol.
=> Add BlockEnergyLimit Update

CHANGELOG.md, app/features/ledger/ConcordiumLedgerClient.ts, app/features/ledger/ConcordiumLedgerClientMain.ts, app/pages/multisig/menu/MultiSignatureCreateProposalList.tsx, app/pages/multisig/updates/FinalizationCommitteeParameters/FinalizationCommitteeParametersShow.tsx, app/pages/multisig/updates/FinalizationCommitteeParameters/FinalizationCommitteeParametersView.tsx, app/pages/multisig/updates/FinalizationCommitteeParameters/UpdateFinalizationCommitteeParameters.tsx, app/pages/multisig/updates/FinalizationCommitteeParameters/util.ts, app/pages/multisig/updates/MintDistribution/UpdateMintDistribution.tsx, app/pages/multisig/updates/TimeParameters/UpdateTimeParameters.tsx, app/preload/ledger/ledger.ts, app/preload/preloadLedgerTypes.ts, app/utils/UpdateSerialization.ts, app/utils/basicHelpers.ts, app/utils/transactionHandlers/FinalizationCommitteeParametersHandler.tsx, app/utils/transactionHandlers/HandlerFinder.ts, app/utils/types.ts
Support the new FinalizationCommitteeParameters Update.
-   Added the flow for the update.
=> Add FinalizationCommitteeParameters Update

CHANGELOG.md, app/features/ledger/ConcordiumLedgerClient.ts, app/features/ledger/ConcordiumLedgerClientMain.ts, app/pages/multisig/menu/MultiSignatureCreateProposalList.tsx, app/pages/multisig/updates/BlockEnergyLimit/UpdateBlockEnergyLimit.tsx, app/pages/multisig/updates/MinBlockTime/MinBlockTimeView.tsx, app/pages/multisig/updates/MinBlockTime/UpdateMinBlockTime.tsx, app/pages/multisig/updates/common/util.ts, app/preload/ledger/ledger.ts, app/preload/preloadLedgerTypes.ts, app/utils/UpdateSerialization.ts, app/utils/transactionHandlers/HandlerFinder.ts, app/utils/transactionHandlers/MinBlockTimeHandler.tsx, app/utils/types.ts
Support the MinBlockTime update.
-  Added the flow for the update.
=> Update minimum block time

CHANGELOG.md, app/features/ledger/ConcordiumLedgerClient.ts, app/features/ledger/ConcordiumLedgerClientMain.ts, app/pages/multisig/common/RelativeRateField/RelativeRateField.tsx, app/pages/multisig/menu/MultiSignatureCreateProposalList.tsx, app/pages/multisig/updates/EuroPerEnergy/UpdateEuroPerEnergy.tsx, app/pages/multisig/updates/MicroGtuPerEuro/UpdateMicroGtuPerEuro.tsx, app/pages/multisig/updates/TimeoutParameters/TimeoutParametersShow.tsx, app/pages/multisig/updates/TimeoutParameters/TimeoutParametersView.tsx, app/pages/multisig/updates/TimeoutParameters/UpdateTimeoutParameters.tsx, app/pages/multisig/updates/TimeoutParameters/util.ts, app/preload/ledger/ledger.ts, app/preload/preloadLedgerTypes.ts, app/utils/UpdateSerialization.ts, app/utils/transactionHandlers/HandlerFinder.ts, app/utils/transactionHandlers/TimeoutParametersHandler.tsx, app/utils/types.ts
Support the `timeout parameters` update.
- Added "no" unit default for `RelativeRateField`.
- Added the flow for the update.
=> Update timeout parameters

CHANGELOG.md, app/pages/multisig/menu/MultiSignatureCreateProposalList.tsx, app/pages/multisig/updates/GasRewards/GasRewardsForm.tsx, app/pages/multisig/updates/GasRewards/GasRewardsView.tsx, app/pages/multisig/updates/GasRewards/UpdateGasRewards.tsx, app/pages/multisig/updates/GasRewards/util.ts, app/pages/multisig/updates/UpdateGovernanceKeys/util.ts, app/utils/UpdateSerialization.ts, app/utils/transactionHandlers/GasRewardsHandler.tsx, app/utils/transactionHandlers/HandlerFinder.ts, app/utils/types.ts
Support updated chain updates for protocol version 6.
-   Support for the new version of the GAS rewards update.
-   Election difficulty authorization is displayed as `Consensus`.
-   Election difficulty update is only shown when protocol is below version 6.
=> Update existing updates

CHANGELOG.md, app/utils/passwordHelpers.ts
Address #193 and #341.
Block single quotes in passwords.
=> Fix crash when quote is in the password (By blocking the choice)

CHANGELOG.md, app/components/ConnectionSettingElement/ConnectionSettingElement.tsx, app/database/migrations/20230920113800_set_default_node_with_grpc2.ts, app/node/nodeConnector.ts, app/node/nodeRequests.ts, app/package.json, app/preload/grpc.ts, app/preload/preloadTypes.ts, app/utils/init/initialize.ts
- Allow choice of SSL/insecure and migrate defaults to grpc v2.
- Bump version.
=> Connection updates

app/components/PickBakerStakeAmount.tsx, app/features/AccountSlice.ts, app/pages/IdentityIssuance/PickProvider/PickProvider.tsx, app/pages/Recovery/util.ts, app/preload/preloadTypes.ts
Unblock identity issuance and recovery.
- Change accountInfo checks to handle error thrown when account does not exist.
- Fixed some types.
=> Fix identity issuance and recovery errors.

app/package.json, app/pages/multisig/common/RelativeRateField/util.ts, app/utils/transactionHandlers/TimeoutParametersHandler.tsx
Allow setting timeout parameters with not reduced fractions.
- Reduce the fractions
=> Ensure timeout parameters are reduced

app/package.json, app/pages/multisig/updates/FinalizationCommitteeParameters/UpdateFinalizationCommitteeParameters.tsx, app/pages/multisig/updates/FinalizationCommitteeParameters/util.ts, app/pages/multisig/updates/TimeoutParameters/TimeoutParametersShow.tsx, app/pages/multisig/updates/TimeoutParameters/UpdateTimeoutParameters.tsx
Fix issues with text in finalization committee and timeout parameters update/display page.
- remove wrong/redundant new labels.
- Remove fraction from relative stake threshold label.
=> Update display/labels of finalization committee and timeout parameters

CHANGELOG.md, app/components/BakerTransactions/BakerStakeSettings.tsx, app/components/Transfers/configureBaker/RemoveBakerPage.tsx, app/components/Transfers/configureDelegation/DelegationAmountPage.tsx, app/components/Transfers/configureDelegation/RemoveDelegationPage.tsx, app/package.json
- edited text on choose stake pages and remove validation/delegation pages.
=> Reword validator/delegator pages to remove use of grace period

CHANGELOG.md, app/package.json
=> Prepare release of 1.8.0

.github/workflows/build-lint-test.yml, .github/workflows/release.yaml, package.json, scripts/desktop-wallet-ci.Dockerfile
Update node version in release workflow, hopefully fixing it :crossed_fingers:
=> Update node version in release workflow
